[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "reset_ancient_card()"
position = "after"
payload = '''
cosmos_reset_pepper_card()'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "reset_ancient_card()"
position = "after"
payload = '''
cosmos_reset_pepper_card()'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "ancient_card = {suit = 'Spades'},"
position = "after"
payload = '''
cosmos_pepper_card = {suit = 'Spades'},'''
match_indent = true
