[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.FUNCS.draw_from_hand_to_discard()"
position = "before"
payload = '''
-- Special thanks to Aure
local context = {cosmos_prepare_cleanup = true}

SMODS.calculate_context(context)

context.cardarea = G.deck
for i = 1, #G.deck.cards do
  local effects = {eval_card(G.deck.cards[i], context)}
  SMODS.calculate_quantum_enhancements(G.deck.cards[i], effects, context)
  SMODS.trigger_effects(effects, G.deck.cards[i])
end
context.cardarea = G.discard
for i = 1, #G.discard.cards do
  local effects = {eval_card(G.discard.cards[i], context)}
  SMODS.calculate_quantum_enhancements(G.discard.cards[i], effects, context)
  SMODS.trigger_effects(effects, G.discard.cards[i])
end

local cosmos_to_destroy = {}

for k, v in ipairs(G.hand.cards) do
    if v.ability.cosmos_destroy_this then
        cosmos_to_destroy[#cosmos_to_destroy+1] = v
    end
end

for i = 1, #G.playing_cards do--, 1, -1 do
    if G.playing_cards[i].area ~= G.hand and G.playing_cards[i].ability.cosmos_destroy_this then
        cosmos_to_destroy[#cosmos_to_destroy+1] = G.playing_cards[i]
    end
end

for k, v in ipairs(G.jokers.cards) do
    if v.ability.cosmos_destroy_this then
        cosmos_to_destroy[#cosmos_to_destroy+1] = v
    end
end

for k, v in ipairs(G.consumeables.cards) do
    if v.ability.cosmos_destroy_this then
        cosmos_to_destroy[#cosmos_to_destroy+1] = v
    end
end

local cosmos_destroy_card = function(card)
    G.E_MANAGER:add_event(Event({
        trigger = 'after',
        delay = 0.2,
        func = function()
            if card and not card.removed then
                if card.ability.name == 'Glass Card' then
                    card:shatter()
                else
                    card:start_dissolve(nil)
                end
            end
            if card.playing_card and G.jokers then
                for j = 1, #G.jokers.cards do
                    eval_card(G.jokers.cards[j], {
                        cardarea = G.jokers,
                        remove_playing_cards = true,
                        removed = {card}
                    })
                end
            end
            return true
        end
    }))
end

if #cosmos_to_destroy and #cosmos_to_destroy > 0 then
    for i = 1, #cosmos_to_destroy do
        cosmos_destroy_card(cosmos_to_destroy[i])
    end
end

if #cosmos_to_destroy and #cosmos_to_destroy > 0 then delay(1.3) end
'''
match_indent = true
